apiVersion: v1
kind: Pod
metadata:
  name: service-list-noauto
  namespace: t23
spec:
  serviceAccountName: api-call
  automountServiceAccountToken: false
  containers:
  - name: service-list
    image: alpine:3.14
    command: ['/bin/sh', '-c']
    args:
    - |
      apk add --no-cache curl && \
      while true; do
        curl -s -k -m 5 \
        -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Im5hNFBhSGU0Um9ZblV0Y244TWItZ0ppejRGOGdfVlFILUpDWkk5Y1AwLUkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzEwNjk3NDY4LCJpYXQiOjE3MTA2OTM4NjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ0MjMiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYXBpLWNhbGwiLCJ1aWQiOiJmZGIzZjQ2ZC1iNzY1LTRiMmMtOWJhNS0yYzhiOTQ2NWYwMDgifX0sIm5iZiI6MTcxMDY5Mzg2OCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnQyMzphcGktY2FsbCJ9.e0cttLGxV90Vb-vxGJzemJqdEdivP0JNqz3ETAYyxW9KIAPMWfnUNOuAV4S_S22Pd9mC4KooF7-MceHkgElCE6prdERav4Y2ETe83H9GwKfEkCTff-xtk1hQaRqucIAO6KWMmjNiOQt1ZqEUAdHSu8yo8KEVrbRBmFhqJM-iYl3gHIqfyeUKXvKK-7saYjPWMFvuHm-Wqdq-dKllFnjXZ9qcTIWiO5Z3pBOgNewlhGNqCnmy1YXVUL67WEcGG6Lr8azOwvZ_b2XmKVSg4x5P4n1mJOSsRkwwT52SQJI1TsV8_geitRJk2JJ-VUsI-gntLUXQjPH3fu9q80QGov8HTA" \
        https://kubernetes.default.svc/api/v1/namespaces/default/services
        sleep 10;
      done

