apiVersion: v1
kind: Pod
metadata:
  name: service-list
  namespace: t23
spec:
  serviceAccountName: api-call
  containers:
  - name: service-list
    image: alpine:3.14
    command: ['/bin/sh', '-c']
    args:
    - |
      apk add --no-cache curl && \
      while true; do
        curl -s -k -m 5 \
        -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
        https://kubernetes.default.svc/api/v1/namespaces/default/services
        sleep 10;
      done

